name: Build and Deploy Website
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies via apt
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-markdown openssh-client sshpass

    - name: Clone LSTE repository
      run: |
        git clone https://github.com/lauratheq/lste.git

    - name: Create .lsterc file
      run: |
        echo "[plugins]" > ~/.lsterc
        echo "active-menu = lauratheq/active-menu.lste" >> ~/.lsterc
        echo "meta = lauratheq/meta.lste" >> ~/.lsterc
        echo "articles = lauratheq/articles.lste" >> ~/.lsterc
        echo "excerpts-markdown = lauratheq/excerpts-markdown.lste" >> ~/.lsterc
        echo "rss = lauratheq/rss.lste" >> ~/.lsterc

    - name: Compile Website
      run: |
        ./lste/lste.py --path=./
        ./lste/lste.py --path=./

    - name: Upload to SFTP server
      run: |
        echo "put -r ./dist/* /test/" > sftp_commands.txt
        sshpass -p ${{ secrets.SFTP_PASSWORD }} sftp -o StrictHostKeyChecking=no -b sftp_commands.txt ${{ secrets.SFTP_USER }}@${{ secrets.SFTP_HOST }}
