name: Build and Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown

    - name: Clone LSTE repository
      run: |
        git clone https://github.com/lauratheq/lste.git

    - name: Create .lsterc file
      run: |
        echo "[plugins]" > ~/.lsterc
        echo "active-menu = lauratheq/active-menu.lste" >> ~/.lsterc
        echo "meta = lauratheq/meta.lste" >> ~/.lsterc
        echo "articles = lauratheq/articles.lste" >> ~/.lsterc
        echo "excerpts-markdown = lauratheq/excerpts-markdown.lste" >> ~/.lsterc
        echo "rss = lauratheq/rss.lste" >> ~/.lsterc

    - name: Test LSTE
      run: |
        ./lste/lste --path=./
